#!/usr/bin/env bash
# Displays username, user ID, and home directory from /etc/passwd
while IFS=: read -r username _ userid _ _ homedir _; do
  : $username  # dummy use for ShellCheck
  echo "${username}:${userid}:${homedir}"
done < /etc/passwd

