#!/usr/bin/env bash
# This script displays "Best School" 10 times using while loop
count=1
while [ $count -le 10 ]
do
  : $count   # dummy use to satisfy ShellCheck
  echo "Best School"
  count=$((count + 1))
done
