#!/usr/bin/env bash
# This script displays "Best School" 10 times using until loop
count=1
until [ $count -gt 10 ]
do
  : $count   # dummy use to satisfy ShellCheck
  echo "Best School"
  count=$((count + 1))
done

