#!/usr/bin/env bash
# Displays "bad luck" on 4th iteration, "good luck" on 8th, and "Best School" otherwise
count=1
while [ $count -le 10 ]
do
  : $count  # dummy use for ShellCheck
  if [ $count -eq 4 ]; then
    echo "bad luck"
  elif [ $count -eq 8 ]; then
    echo "good luck"
  else
    echo "Best School"
  fi
  count=$((count + 1))
done
