#!/usr/bin/env bash
# Displays numbers from 1 to 20 with superstitions for specific numbers
count=1
while [ $count -le 20 ]
do
  : $count  # dummy use for ShellCheck
  echo "$count"
  case $count in
    4) echo "bad luck from China" ;;
    9) echo "bad luck from Japan" ;;
    17) echo "bad luck from Italy" ;;
  esac
  count=$((count + 1))
done
