#!/usr/bin/env bash
# Displays hours 0-12 and minutes 1-59
hour=0
while [ $hour -le 12 ]
do
  : $hour  # dummy use for ShellCheck
  echo "Hour: $hour"
  minute=1
  while [ $minute -le 59 ]
  do
    : $minute  # dummy use for ShellCheck
    echo "$minute"
    minute=$((minute + 1))
  done
  hour=$((hour + 1))
done
